// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import localFont from 'next/font/local'
import { ThemeProvider } from "@/components/ThemeProvider";


// Подключаем Space Grotesk (для заголовков и хедера)
const spaceGrotesk = localFont({
  src: "../public/fonts/SpaceGrotesk/SpaceGrotesk.ttf", // Проверь имя файла!
  variable: "--font-space-grotesk",
});

// Подключаем Inter (для основного текста)
const inter = localFont({
  src: "../public/fonts/Inter/Inter-Regular.otf", // Проверь имя файла!
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Profiler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>

      <body
        className={`${spaceGrotesk.variable} ${inter.variable} antialiased`}
      >
        <ThemeProvider>
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
